export const accountsData = [
  {
    id: 1,
    name: "Conto Corrente",
    type: "checking",
    bank: "Intesa Sanpaolo",
    balance: 4250.5,
    currency: "EUR",
    lastTransaction: "2024-11-15",
    status: "active",
    accountNumber: "****1234",
    isPrimary: true,
  },
  {
    id: 2,
    name: "Conto Risparmio",
    type: "savings",
    bank: "UniCredit",
    balance: 12800.0,
    currency: "EUR",
    lastTransaction: "2024-11-10",
    status: "active",
    accountNumber: "****5678",
    isPrimary: false,
  },
  {
    id: 3,
    name: "Carta di Credito",
    type: "credit",
    bank: "American Express",
    balance: -850.25,
    currency: "EUR",
    lastTransaction: "2024-11-16",
    status: "active",
    accountNumber: "****9012",
    isPrimary: false,
  },
  {
    id: 4,
    name: "Conto Investimenti",
    type: "investment",
    bank: "Fineco",
    balance: 25600.75,
    currency: "EUR",
    lastTransaction: "2024-11-14",
    status: "active",
    accountNumber: "****3456",
    isPrimary: false,
  },
  {
    id: 5,
    name: "Conto Business",
    type: "business",
    bank: "BPER Banca",
    balance: 8950.3,
    currency: "EUR",
    lastTransaction: "2024-11-12",
    status: "active",
    accountNumber: "****7890",
    isPrimary: false,
  },
];

export const recentTransactions = [
  {
    id: 1,
    account: "Conto Corrente",
    description: "Stipendio",
    amount: 3200,
    type: "income",
    date: "2024-11-15",
  },
  {
    id: 2,
    account: "Carta di Credito",
    description: "Spesa supermercato",
    amount: -85.5,
    type: "expense",
    date: "2024-11-16",
  },
  {
    id: 3,
    account: "Conto Risparmio",
    description: "Trasferimento",
    amount: 500,
    type: "transfer",
    date: "2024-11-10",
  },
  {
    id: 4,
    account: "Conto Investimenti",
    description: "Dividendi ETF",
    amount: 125.3,
    type: "income",
    date: "2024-11-14",
  },
  {
    id: 5,
    account: "Conto Business",
    description: "Fattura cliente",
    amount: 1200,
    type: "income",
    date: "2024-11-12",
  },
];
