export const accountsData = [
  {
    id: 1,
    name: "Conto Corrente Principale",
    type: "checking",
    bank: "Intesa Sanpaolo",
  },
  { id: 2, name: "Conto Risparmio", type: "savings", bank: "UniCredit" },
  { id: 3, name: "Carta di Credito", type: "credit", bank: "American Express" },
  { id: 4, name: "Conto Investimenti", type: "investment", bank: "Fineco" },
  { id: 5, name: "Conto Business", type: "business", bank: "BPER Banca" },
];

export const transactionsData = {
  1: [
    {
      id: 1,
      description: "Stipendio Novembre",
      amount: 3200,
      type: "income",
      date: "2024-11-15",
      category: "Lavoro",
    },
    {
      id: 2,
      description: "Affitto",
      amount: -1200,
      type: "expense",
      date: "2024-11-01",
      category: "Casa",
    },
    {
      id: 3,
      description: "Spesa supermercato",
      amount: -85.5,
      type: "expense",
      date: "2024-11-14",
      category: "Alimentari",
    },
    {
      id: 4,
      description: "Bonifico da amico",
      amount: 50,
      type: "income",
      date: "2024-11-12",
      category: "Personale",
    },
    {
      id: 5,
      description: "Carburante",
      amount: -65,
      type: "expense",
      date: "2024-11-10",
      category: "Trasporti",
    },
    {
      id: 6,
      description: "Cena ristorante",
      amount: -45,
      type: "expense",
      date: "2024-11-08",
      category: "Svago",
    },
    {
      id: 7,
      description: "Freelance",
      amount: 800,
      type: "income",
      date: "2024-11-05",
      category: "Lavoro",
    },
    {
      id: 8,
      description: "Bolletta luce",
      amount: -120,
      type: "expense",
      date: "2024-11-03",
      category: "Utenze",
    },
  ],
  2: [
    {
      id: 9,
      description: "Trasferimento da corrente",
      amount: 500,
      type: "transfer",
      date: "2024-11-10",
      category: "Trasferimento",
    },
    {
      id: 10,
      description: "Interessi maturati",
      amount: 12.5,
      type: "income",
      date: "2024-11-01",
      category: "Interessi",
    },
  ],
  3: [
    {
      id: 11,
      description: "Spesa online",
      amount: -150,
      type: "expense",
      date: "2024-11-16",
      category: "Shopping",
    },
    {
      id: 12,
      description: "Ristorante",
      amount: -75,
      type: "expense",
      date: "2024-11-13",
      category: "Svago",
    },
    {
      id: 13,
      description: "Pagamento rata auto",
      amount: -320,
      type: "expense",
      date: "2024-11-05",
      category: "Trasporti",
    },
  ],
  4: [
    {
      id: 14,
      description: "Dividendi ETF",
      amount: 125.3,
      type: "income",
      date: "2024-11-14",
      category: "Investimenti",
    },
    {
      id: 15,
      description: "Acquisto azioni",
      amount: -1000,
      type: "expense",
      date: "2024-11-08",
      category: "Investimenti",
    },
  ],
  5: [
    {
      id: 16,
      description: "Fattura cliente A",
      amount: 1200,
      type: "income",
      date: "2024-11-12",
      category: "Business",
    },
    {
      id: 17,
      description: "Spese ufficio",
      amount: -200,
      type: "expense",
      date: "2024-11-09",
      category: "Business",
    },
    {
      id: 18,
      description: "Software subscription",
      amount: -99,
      type: "expense",
      date: "2024-11-01",
      category: "Business",
    },
  ],
};
